KWLMobileQuery/Controllers/NLogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KWLMobileQuery.Connections;
using KWLMobileQuery.Models;

namespace KWLMobileQuery.Controllers
{
    [Authorize]
    public class NLogsController : Controller
    {
        private UserManagementAPIEntities db = new UserManagementAPIEntities();

        // GET: NLogs
        public ActionResult Index()
        {
            return View((from p in db.NLogs
                         where p.UserName == Classes.UserCls.i_user.UserName
                         orderby p.ID descending
                         select p).Take(50).ToList());
        }

       
        public ActionResult Anon()
        {
            string frTimeStr = Request.QueryString["fr"];
            string toTimeStr = Request.QueryString["to"];
            string sl = Request.QueryString["sl"];

            DateTime fromTime;
            var isValidFromDate = DateTime.TryParseExact(frTimeStr, "MM/dd/yyyy h:mm tt", CultureInfo.InvariantCulture, DateTimeStyles.None, out fromTime);
            if (!isValidFromDate) fromTime = DateTime.Now;

            DateTime toTime;
            var isValidToDate = DateTime.TryParseExact(toTimeStr, "MM/dd/yyyy h:mm tt", CultureInfo.InvariantCulture, DateTimeStyles.None, out toTime);
            if (!isValidToDate) toTime = DateTime.Now;

            ViewBag.SearchFrom = (DateTime)fromTime;
            ViewBag.SearchTo = (DateTime)toTime;

            ViewBag.Levels = "Error,Info";
            ViewBag.level = sl;

            var xlist = db.NLogs.Where(p => p.Logged >= fromTime && p.Logged <= toTime &&
                                          (p.UserName == null || p.UserName.Equals(string.Empty)));
                                   

            if (!String.IsNullOrEmpty(sl))
            {
               xlist =  xlist.Where(p => p.Level == sl);
            }

            return View(xlist.OrderByDescending(p=>p.Logged).Take(100).ToList());


        }

        // GET: NLogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NLog nLog = db.NLogs.Find(id);
            if (nLog == null)
            {
                return HttpNotFound();
            }
            return View(nLog);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KWLMobileQuery/Views/Shared/_DateRangeControl.cshtml
<div class="row">
    <div class="col-md-offset-6">
        <form class="form-horizontal" id="searchForm">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-sm-2" for="Level">Level</label>
                <div class="col-sm-10">
                    <select class="form-control input-sm" id="SearchLevel" name="SearchLevel"></select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="SearchFrom">From</label>
                <div class="col-sm-10">
                    <div class='input-group date' id='SearchFrom'>
                        <input type='text' class="form-control" />
                        <span class="input-group-addon">
                            <span class="fa fa-calendar">
                            </span>
                        </span>
                    </div>


                    @*<input type="text" class="form-control input-sm" id="SearchFrom" name="SearchFrom" />*@
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="SearchTo">To</label>
                <div class="col-sm-10">
                    <div class='input-group date' id='SearchTo'>
                        <input type='text' class="form-control" />
                        <span class="input-group-addon">
                            <span class="fa fa-calendar">
                            </span>
                        </span>
                    </div>

                    @*<input type="text" class="form-control input-sm" id="SearchTo" name="SearchTo" />*@
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

KWLMobileQuery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("KWL Mobile Query", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_MenuLayout")
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="active"><a>@User.Identity.Name<span class="sr-only">(current)</span></a></li>
                        <li> @Html.ActionLink("Logout", "LogOff", "Account")</li>
                    }
                    else
                    {
                        <li> @Html.ActionLink("Login", "Login", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <br />
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - KWL Mobile App Query</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

KWLMobileQuery/Views/Shared/_MenuLayout.cshtml
@using KWLMobileQuery.Classes;
<ul class="nav navbar-nav">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    @if(User.Identity.IsAuthenticated){
        <li>@Html.ActionLink("APM Logs", "Index", "Logs")</li>
        <li>@Html.ActionLink("A-User Logs", "Anon", "Nlogs", null, new { title = "Anonymous user Logs" })</li>
        <li>@Html.ActionLink("Users", "Index", "Users")</li>
    }
    @if (@UserCls.i_user != null)
    {
        <li> @Html.ActionLink("Users Logs", "Index", "NLogs", null, new { title = "Logged-In User Logs" })</li>
        <li> @Html.ActionLink("Payments", "Index", "Payments")</li>
    }
</ul>

KWLMobileQuery/Views/Shared/_UserDetails.cshtml
@using KWLMobileQuery.Classes;
<ul class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li> @Html.ActionLink("Users", "Index", "Users")</li>
    @if (ViewBag.UserDetailView == null)
    {
        <li> @Html.ActionLink("User Details", "Details", "Users", new { id = @UserCls.i_user.Id }, null)</li>
    }
    @if (ViewBag.ParentUrl != null)
    {
        <li><a href="@ViewBag.ParentUrl">@ViewBag.ParentTitle</a></li>
    }
    <li>@ViewBag.Title</li>
</ul>

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-md-12">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#collapse1">User Details</a>
                    </h4>
                </div>
                <div id="collapse1" class="panel-collapse collapse">                   
                    <div class="panel-body">
                        <div class="rows">
                            <div class="col-md-6">
                                <dl class="dl-horizontal">
                                    <dt>
                                        UserName
                                    </dt>

                                    <dd>
                                        @UserCls.i_user.UserName
                                    </dd>
                                    <dt>
                                        First Name
                                    </dt>

                                    <dd>
                                        @UserCls.i_user.FirstName
                                    </dd>

                                    <dt>
                                        Last Name
                                    </dt>

                                    <dd>
                                        @UserCls.i_user.LastName
                                    </dd>

                                    <dt>
                                        Email
                                    </dt>
                                    <dd>
                                        @UserCls.i_user.Email
                                    </dd>
                                    <dt>
                                        Email Confirmed
                                    </dt>
                                    <dd>
                                        @UserCls.i_user.EmailConfirmed
                                    </dd>
                                    <dt>
                                        Phone Number
                                    </dt>

                                    <dd>
                                        @UserCls.i_user.PhoneNumber
                                    </dd>

                                    <dt>
                                        Phone Confirmed
                                    </dt>

                                    <dd>
                                        @UserCls.i_user.PhoneNumberConfirmed
                                    </dd>

                                    <dt>
                                        Access Failed Count
                                    </dt>

                                    <dd>
                                        @Html.DisplayFor(model => @UserCls.i_user.AccessFailedCount)
                                    </dd>
                                </dl>

                            </div>
                            <div class="col-md-6">
                                <h4>Associated Links</h4>
                                <ul>
                                    <li> @Html.ActionLink("Users Logs", "Index", "NLogs")</li>
                                    <li> @Html.ActionLink("Payments", "Index", "Payments")</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer"></div>
                </div>
            </div>
        </div>
    </div>
</div>